# SakuraCmd Configuration File!
# @author syamn <admin@sakura-server.net>
# github: https://github.com/SakuraServer/SakuraCmd

#====================#
#   General Config   #
#====================#
UseNamePrefix: true
UseDisplayName: true
AfkCheckIntervalInSec: 30

#========================#
#   Permission Control   #
#========================#
# Supported controller: PermissionsEx, SuperPerms
Permission: "PermissionsEx"

#==================#
#   Debug Config   #
#==================#
Debug: false

#==================#
#   DO NOT TOUCH   #
#==================#
# Do not touch this option! It is a check if you are running the recent configuration version
ConfigVersion: 1