##  Plugin Information  ##
name: SakuraCmd
version: version-number-unknown
main: net.syamn.sakuracmd.SakuraCmd
description: Minecraft SakuraCmd server plugin
website: http://sakura-server.net/
##  Original Author     ##
author: syamn
