##  Plugin Information  ##
name: SakuraCmd
version: version-number-unknown
main: net.syamn.sakuracmd.SakuraCmd
description: Minecraft SakuraCmd server plugin
website: http://sakura-server.net/
softdepend: [Vault]
##  Original Author     ##
author: syamn
commands:
    repairall:
      usage: /repairall - to see the help
      description: See plugin help.
    repairitem:
      usage: /repairitem - to see the help
      description: See plugin help.
    tp:
      usage: /tp - to see the help
      description: See plugin help.
    tphere:
      usage: /tphere - to see the help
      description: See plugin help.
    lockdown:
      usage: /lockdown - to see the help
      description: See plugin help.
    afk:
      usage: /afk - to see the help
      description: See plugin help.
    sakuracmd:
      usage: /sakuracmd - to see the help
      aliases: [sakuracmd]
      description: To see the plugin help.
permissions:
    sakuracmd.admin:
        default: op
        description: Give to admins