##  Plugin Information  ##
name: SakuraCmd
version: version-number-unknown
main: net.syamn.sakuracmd.SakuraCmd
description: Minecraft SakuraCmd server plugin
website: http://sakura-server.net/
softdepend: [PermissionsEx, dynmap, Vault, MCBans]
##  Original Author     ##
author: syamn
commands:
    repairall:
      usage: /repairall - to see the help
      description: See plugin help.
    repairitem:
      usage: /repairitem - to see the help
      description: See plugin help.
    tp:
      usage: /tp - to see the help
      description: See plugin help.
    tphere:
      usage: /tphere - to see the help
      description: See plugin help.
    tploc:
      usage: /tploc - to see the help
      description: See plugin help.
    ride:
      usage: /ride - to see the help
      description: See plugin help.
    back:
      usage: /back - to see the help
      description: See plugin help.
    lockdown:
      usage: /lockdown - to see the help
      description: See plugin help.
    afk:
      usage: /afk - to see the help
      description: See plugin help.
    invisible:
      usage: /invisible - to see the help
      description: See plugin help.
    god:
      usage: /god - to see the help
      aliases: [g]
      description: See plugin help.
    gamemode:
      usage: /gamemode - to see the help
      aliases: [gm]
      description: See plugin help.
    fly:
      usage: /fly - to see the help
      description: See plugin help.
    flymode:
      usage: /flymode - to see the help
      aliases: [fm]
      description: See plugin help.
    weather:
      usage: /weather - to see the help
      description: See plugin help.
    mail:
      usage: /mail - to see the help
      aliases: [ml]
      description: To see the plugin help.
    whois:
      usage: /whois - to see the help
      description: See plugin help.
    openinv:
      usage: /openinv - to see the help
      description: See plugin help.
    openender:
      usage: /openender - to see the help
      description: See plugin help.
    register:
      usage: /register - to see the help
      aliases: [webregister]
      description: See plugin help.
    password:
      usage: /password - to see the help
      aliases: [passwd]
      description: See plugin help.
    mfmf:
      usage: /mfmf - to see the help
      aliases: [もふもふ]
      description: To see the plugin help.
    confirm:
      usage: /confirm - to see the help
      aliases: [sakuraconfirm]
      description: To see the plugin help.
    admin:
      usage: /admin - to see the help
      description: To see the plugin help.
    sakuracmd:
      usage: /sakuracmd - to see the help
      aliases: [sakuracommand]
      description: To see the plugin help.
    colors:
      usage: /colors - to see the help
      aliases: [col]
      description: To see the plugin help.
    web:
      usage: /web - to see the help
      description: To see the plugin help.
permissions:
    sakuracmd.admin:
        default: op
        description: Give to admins